name: Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ github.ref_name }}
          push: true
          tags: |
            1234567890.dkr.ecr.us-east-2.amazonaws.com/service:${{ github.ref_name }}
            1234567890.dkr.ecr.us-east-2.amazonaws.com/service:latest
